### ISSUE TITLE
[DESIGN] init home wild-frame design

### ISSUE THREAD

**Issue by eunbeek** [YourMoneyMyMoney/ymmm_ui#1]
- main home 화면 기반으로 wild-frame design
- figma로 공유 되면 가장 좋음
- 화면 기본 비율 (하단참조)
[MacOS]
[Windows]
[iOS]
[Android]

**Comment by Sunyoung192** [comment]
https://www.figma.com/file/WEpjv1KLK1zcx9E88amtXZ/Untitled?type=design&node-id=0%3A1&mode=design&t=jWgeQELIK51sphSu-1
